# dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-prod-ns
resources:
  - namespace.yaml
bases:
  - ../../base
patchesStrategicMerge:
  - replica_patch.yaml
configMapGenerator:
- name: web-app-config
  literals:
    - hostname=prod-db.devoriales.com
    - port=5432
    - dbname=webapp-prod
secretGenerator:
- name: web-app-credentials
  literals:
    - username=prod-user
    - password=prod-password
