apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-prod-ns
resources:
  - namespace.yaml
bases:
- ../../base
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: nginx
  spec:
    replicas: 3
# create configmap
configMapGenerator:
- name: my-config
  files:
    - prod-config.properties
# create secret
secretGenerator:
- name: my-secret
  files:
    - prod-secret.txt
